name: BuildnPush

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      IMAGE_REGISTRY:
        required: true
        type: string

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  image-build-n-push:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    name: Build multi-arch container image and push to registry
    env:
      IMAGE_REGISTRY: ${{ inputs.IMAGE_REGISTRY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${GITHUB_ACTOR,,} --password-stdin

      - name: Build and push multi-arch image
        run: |
          IMAGE_REGISTRY="${{ env.IMAGE_REGISTRY }}" make docker-build-push
